services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hotel_erp_db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "${MSSQL_PID}"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      MSSQL_TCP_PORT: 1433
    ports:
      - "${MSSQL_PORT}:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P \"$${MSSQL_SA_PASSWORD}\" -Q \"SELECT 1\" || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s

  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hotel_erp_db_init
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    volumes:
      - ./db/HotelManagementDB.sql:/scripts/HotelManagementDB.sql:ro
    entrypoint: /bin/bash
    command: >
      -lc "
      set -e;
      echo 'Waiting for SQL Server...';
      for i in {1..60}; do
        /opt/mssql-tools18/bin/sqlcmd -C -S sqlserver -U sa -P \"$$MSSQL_SA_PASSWORD\" -Q \"SELECT 1\" && break;
        echo 'SQL Server not ready yet...';
        sleep 2;
      done;
      echo 'Running HotelManagementDB.sql...';
      /opt/mssql-tools18/bin/sqlcmd -b -C -S sqlserver -U sa -P \"$$MSSQL_SA_PASSWORD\" -i /scripts/HotelManagementDB.sql;
      echo 'Database initialized successfully.';
      "
    restart: "no"

  redis:
    image: redis:latest
    container_name: hotel_erp_redis
    ports:
      - "6380:6379"
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: ./HotelERP.BE/Dockerfile
    container_name: hotel_erp_api
    depends_on:
      db-init:
        condition: service_completed_successfully
      # Phải bảo API chờ Redis chạy lên nữa:
      redis:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=HotelManagementDB;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=True"
      # Thêm chuỗi kết nối Redis cho App C# hiểu khi chạy trong Docker:
      RedisConnection: "redis:6379,abortConnect=false"
    ports:
      - "8081:8080"
    restart: unless-stopped

volumes:
  sql_data: